import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { AppRoutingModule } from "@src/app/app-routing.module";
import { AppComponent } from "@src/app/app.component";
import { AutoGeneratedComponent } from "@src/app/auto-generated/auto-generated.component";
import { ReaderComponent } from "@src/app/reader/reader.component";
import { LayoutComponent } from "@src/app/layout/layout.component";
import { HomeComponent } from "@src/app/home/home.component";
import { LibraryComponent } from "@src/app/library/library.component";
import { CatalogsComponent } from "@src/app/catalogs/catalogs.component";
import { SettingsComponent } from "@src/app/settings/settings.component";
import { SearchResultsComponent } from "@src/app/search-results/search-results.component";
import { WebSheetComponent } from "@src/app/web-sheet/web-sheet.component";
import { WebResultsComponent } from "@src/app/web-results/web-results.component";
import { CatalogFormComponent } from "@src/app/catalog-form/catalog-form.component";
import { FeedComponent } from "@src/app/feed/feed.component.tns";
import { BookSheetComponent } from "@src/app/book-sheet/book-sheet.component";

@NgModule({
	declarations: [
		AppComponent,
		AutoGeneratedComponent,
		ReaderComponent,
		LayoutComponent,
		HomeComponent,
		LibraryComponent,
		CatalogsComponent,
		SettingsComponent,
		SearchResultsComponent,
		WebSheetComponent,
		WebResultsComponent,
		CatalogFormComponent,
		FeedComponent,
		BookSheetComponent
	],
	imports: [
		BrowserModule,
		AppRoutingModule
	],
	providers: [],
	bootstrap: [AppComponent]
})
export class AppModule { }
