import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { ReaderComponent } from '@src/app/reader/reader.component';
import { LayoutComponent } from '@src/app/layout/layout.component.base';
import { HomeComponent } from '@src/app/home/home.component';
import { LibraryComponent } from '@src/app/library/library.component';
import { CatalogsComponent } from '@src/app/catalogs/catalogs.component';
import { SettingsComponent } from '@src/app/settings/settings.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    ReaderComponent,
    LayoutComponent,
    HomeComponent,
    LibraryComponent,
    CatalogsComponent,
    SettingsComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
